/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/admin/anime/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          sort?: 'createdAt';
          order?: 'asc' | 'desc';
          status?: ('draft' | 'upcoming' | 'airing' | 'completed')[];
          types?: ('movie' | 'japanese' | 'american' | 'chinese' | 'adult')[];
          tags?: number[];
          years?: (
            | '1990'
            | '1991'
            | '1992'
            | '1993'
            | '1994'
            | '1995'
            | '1996'
            | '1997'
            | '1998'
            | '1999'
            | '2000'
            | '2001'
            | '2002'
            | '2003'
            | '2004'
            | '2005'
            | '2006'
            | '2007'
            | '2008'
            | '2009'
            | '2010'
            | '2011'
            | '2012'
            | '2013'
            | '2014'
            | '2015'
            | '2016'
            | '2017'
            | '2018'
            | '2019'
            | '2020'
            | '2021'
            | '2022'
            | '2023'
            | '2024'
            | '2025'
            | '2026'
            | '2027'
          )[];
          months?: ('january' | 'april' | 'july' | 'october')[];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  seriesId: number;
                  name: string;
                  description: string;
                  remark: string;
                  cover: string;
                  banner: string;
                  /** @enum {string} */
                  status: 'draft' | 'upcoming' | 'airing' | 'completed';
                  /** @enum {string} */
                  type: 'movie' | 'japanese' | 'american' | 'chinese' | 'adult';
                  year: number;
                  /** @enum {string} */
                  month: 'january' | 'april' | 'july' | 'october';
                  director: string;
                  cv: string;
                  season: number;
                  seasonName: string | null;
                  avgScore: number;
                  scoreCount: number;
                  tags: {
                    id: number;
                    name: string;
                  }[];
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            seriesId: number;
            name: string;
            description: string;
            remark: string;
            cover: string;
            banner: string;
            /** @enum {string} */
            status: 'draft' | 'upcoming' | 'airing' | 'completed';
            /** @enum {string} */
            type: 'movie' | 'japanese' | 'american' | 'chinese' | 'adult';
            year: number;
            /** @enum {string} */
            month: 'january' | 'april' | 'july' | 'october';
            director: string;
            cv: string;
            season: number;
            seasonName?: string;
            tags: number[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/anime/options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                label: string;
                value: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/anime/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            seriesId?: number;
            name?: string;
            description?: string;
            remark?: string;
            cover?: string;
            banner?: string;
            /** @enum {string} */
            status?: 'draft' | 'upcoming' | 'airing' | 'completed';
            /** @enum {string} */
            type?: 'movie' | 'japanese' | 'american' | 'chinese' | 'adult';
            year?: number;
            /** @enum {string} */
            month?: 'january' | 'april' | 'july' | 'october';
            director?: string;
            cv?: string;
            season?: number;
            seasonName?: string;
            tags?: number[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/collections/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          sort?: 'createdAt';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  userId: number;
                  animeId: number;
                  user: {
                    name: string;
                  };
                  anime: {
                    name: string;
                    cover: string;
                  };
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/collections/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/danmaku/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          mode?: 'scroll' | 'top' | 'bottom';
          sort?: 'createdAt' | 'time';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  user: {
                    name: string;
                  };
                  anime: {
                    name: string;
                    cover: string;
                  };
                  text: string;
                  /** @enum {string} */
                  mode: 'scroll' | 'top' | 'bottom';
                  color: string;
                  time: number;
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/danmaku/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/dashboard/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                content: {
                  animeTotal: number;
                  animeByStatus: {
                    draft: number;
                    upcoming: number;
                    airing: number;
                    completed: number;
                  };
                  animeByType: {
                    movie: number;
                    japanese: number;
                    american: number;
                    chinese: number;
                    adult: number;
                  };
                  videoTotal: number;
                  seriesTotal: number;
                  topicTotal: number;
                };
                users: {
                  total: number;
                  active: number;
                  byRole: {
                    admin: number;
                    premium: number;
                    user: number;
                    guest: number;
                  };
                };
                interaction: {
                  danmakuTotal: number;
                  historyTotal: number;
                  collectionTotal: number;
                  scoreTotal: number;
                };
                tasks: {
                  pending: number;
                  completed: number;
                };
                pending: {
                  feedbacks: number;
                };
                topCollections: {
                  animeId: number;
                  animeName: string;
                  cover: string;
                  count: number;
                }[];
                recentFeedbacks: {
                  id: number;
                  animeName: string;
                  type: string;
                  content: string;
                  /** Format: date-time */
                  createdAt: string;
                }[];
                recentScores: {
                  id: number;
                  userName: string;
                  animeName: string;
                  score: number;
                  content: string;
                  /** Format: date-time */
                  createdAt: string;
                }[];
                system: {
                  database: {
                    /** @enum {string} */
                    status: 'ok' | 'error';
                    latency?: number;
                  };
                  redis: {
                    /** @enum {string} */
                    status: 'ok' | 'error';
                    latency?: number;
                  };
                };
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/feedbacks/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          type?: ('consultation' | 'suggestion' | 'complaint' | 'other')[];
          status?: ('pending' | 'processing' | 'done')[];
          sort?: 'createdAt';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  userId: number;
                  animeId: number;
                  anime: {
                    name: string;
                    cover: string;
                  };
                  user: {
                    name: string;
                  };
                  /** @enum {string} */
                  type: 'consultation' | 'suggestion' | 'complaint' | 'other';
                  content: string;
                  /** @enum {string} */
                  status: 'pending' | 'processing' | 'done';
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/feedbacks/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            type?: 'consultation' | 'suggestion' | 'complaint' | 'other';
            content?: string;
            /** @enum {string} */
            status?: 'pending' | 'processing' | 'done';
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/files/tree': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          path?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                name: string;
                path: string;
                hasChildren: boolean;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/histories/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          sort?: 'createdAt' | 'time';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  user: {
                    name: string;
                  };
                  anime: {
                    name: string;
                    cover: string;
                  };
                  time: number;
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/histories/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/mcp/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                endpoint: string;
                tokenEnabled: boolean;
                tools: {
                  name: string;
                  description: string;
                }[];
                guide: string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/resources/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  title: string;
                  magnet: string;
                  size: number;
                  fansub?: string | null;
                  createdAt: string;
                }[];
                hasMore: boolean;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/scores/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          status?: ('true' | 'false')[];
          sort?: 'createdAt';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  userId: number;
                  animeId: number;
                  score: number;
                  content: string;
                  status: boolean;
                  user: {
                    name: string;
                  };
                  anime: {
                    name: string;
                    cover: string;
                  };
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/scores/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            status: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/scrape/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          query: string;
          language?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                tmdbId: number;
                /** @enum {string} */
                mediaType: 'tv' | 'movie';
                name: string;
                overview: string;
                cover: string | null;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/scrape/detail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          tmdbId: number;
          mediaType?: 'tv' | 'movie';
          season?: number;
          language?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                name: string;
                description: string;
                cover: string | null;
                banner: string | null;
                /** @enum {string} */
                status: 'draft' | 'upcoming' | 'airing' | 'completed';
                /** @enum {string} */
                type: 'movie' | 'japanese' | 'american' | 'chinese' | 'adult';
                year: number;
                /** @enum {string} */
                month: 'january' | 'april' | 'july' | 'october';
                director: string;
                cv: string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/series/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          sort?: 'createdAt';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  name: string;
                  anime: {
                    id: number;
                    name: string;
                    season: number;
                  }[];
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/series/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/series/options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                label: string;
                value: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                server: {
                  nodeVersion: string;
                  environment: string;
                  uptime: number;
                  port: number;
                  adminEmail: string;
                };
                qbit: {
                  host: string;
                  downloadPath: string;
                  hostDownloadPath: string;
                };
                smtp: {
                  host: string;
                  port: number;
                  secure: boolean;
                  from: string;
                };
                database: {
                  poolMax: number;
                  poolIdleTimeout: number;
                  poolConnectionTimeout: number;
                };
                session: {
                  maxAge: number;
                  renewThreshold: number;
                  domain: string;
                };
                security: {
                  rateLimitMax: number;
                  corsOrigins: string;
                };
                resource: {
                  rootPath: string;
                };
                tmdb: {
                  imageDomain: string;
                  apiDomain: string;
                };
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/cache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tags/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          sort?: 'createdAt';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  name: string;
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tags/options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                label: string;
                value: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tasks/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          status?: ('pending' | 'completed')[];
          sort?: 'createdAt' | 'fileSize';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  filename: string;
                  fileSize: number;
                  /** @enum {string} */
                  status: 'pending' | 'completed';
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tasks/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tasks/ingest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            id: number;
            path: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/topics/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          status?: ('true' | 'false')[];
          sort?: 'createdAt';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  name: string;
                  description: string;
                  status: boolean;
                  cover: string;
                  anime: {
                    id: number;
                    name: string;
                  }[];
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            description: string;
            status: boolean;
            cover: string;
            animeIds?: number[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/topics/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            description?: string;
            status?: boolean;
            cover?: string;
            animeIds?: number[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/torrents/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          status?:
            | 'downloading'
            | 'metaDL'
            | 'forcedDL'
            | 'stalledDL'
            | 'checkingDL'
            | 'queuedDL'
            | 'pausedDL'
            | 'allocating'
            | 'uploading'
            | 'forcedUP'
            | 'stalledUP'
            | 'checkingUP'
            | 'queuedUP'
            | 'pausedUP'
            | 'error'
            | 'missingFiles'
            | 'moving'
            | 'checkingResumeData'
            | 'unknown';
          sort?: 'size' | 'added_on';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  name: string;
                  /** @enum {string} */
                  status:
                    | 'downloading'
                    | 'metaDL'
                    | 'forcedDL'
                    | 'stalledDL'
                    | 'checkingDL'
                    | 'queuedDL'
                    | 'pausedDL'
                    | 'allocating'
                    | 'uploading'
                    | 'forcedUP'
                    | 'stalledUP'
                    | 'checkingUP'
                    | 'queuedUP'
                    | 'pausedUP'
                    | 'error'
                    | 'missingFiles'
                    | 'moving'
                    | 'checkingResumeData'
                    | 'unknown';
                  progress: number;
                  size: number;
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            torrentUrl: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          role?: ('admin' | 'premium' | 'user' | 'guest')[];
          status?: ('true' | 'false')[];
          sort?: 'createdAt';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  name: string;
                  email: string;
                  /** @enum {string} */
                  role: 'admin' | 'premium' | 'user' | 'guest';
                  status: boolean;
                  avatar?: string | null;
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            /** @enum {string} */
            role?: 'admin' | 'premium' | 'user' | 'guest';
            status?: boolean;
            avatar?: string | null;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/videos/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          keyword?: string;
          sort?: 'createdAt' | 'episode' | 'views';
          order?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  animeId: number;
                  anime: {
                    name: string;
                    cover: string;
                  };
                  title: string;
                  episode: number;
                  url: string;
                  views: number;
                  /** Format: date-time */
                  createdAt: string;
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            animeId: number;
            title: string;
            episode: number;
            url: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/videos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            animeId?: number;
            title?: string;
            episode?: number;
            url?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                id: number;
                /** Format: email */
                email: string;
                name: string;
                /** @enum {string} */
                role: 'admin' | 'premium' | 'user' | 'guest';
                avatar: string | null;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/send-code': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            code: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                id: number;
                /** Format: email */
                email: string;
                name: string;
                /** @enum {string} */
                role: 'admin' | 'premium' | 'user' | 'guest';
                avatar: string | null;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/client/search/suggestions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          keyword: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                name: string;
                highlightName: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/client/search/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          keyword: string;
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                items: {
                  id: number;
                  name: string;
                  description: string;
                  cover: string;
                  status: string;
                  type: string;
                  director: string;
                  cv: string;
                  year: number;
                  month: string;
                  tags: string[];
                  avgScore: number;
                  scoreCount: number;
                  videoCount: number;
                  videoId: number | null;
                  highlightName: string;
                  videos: {
                    id: number;
                    episode: number;
                  }[];
                }[];
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Health check endpoint */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {number} */
              code: 200;
              message: string;
              data: {
                status: string;
                timestamp: number;
                uptime: number;
                environment: string;
                database: {
                  status: string;
                  latency?: number;
                };
                redis: {
                  status: string;
                  latency?: number;
                };
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mcp/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/webhook/qbit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query: {
          hash: string;
          tag?: string;
          token: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
